root = "."
tmp_dir = "/build"

[build]
  cmd = "go build -o /build/main ."
  bin = "/build/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets"]

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
